config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'tasks', to: 'tasks#index'

  get 'tasks/new', to: 'tasks#new'
  post 'tasks', to: 'tasks#create'

  get 'tasks/:id', to: 'tasks#show', as: :task

  get 'tasks/:id/edit', to: 'tasks#edit', as: :edit_task
  patch 'tasks/id', to: 'tasks#update'

  delete 'tasks/:id', to: 'tasks#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    # GET /restaurants
    @tasks = Task.all
  end

  def show
    # GET /restaurants/:id
    @task = Task.find(params[:id])
  end

  def new
    # GET /restaurants/new
    @task = Task.new
  end

  def create
    # POST /restaurants
    @task = Task.new(task_params)
    @task.save
    redirect_to task_path(@task)
  end

  def edit
    # GET /restaurants/:id/edit
    @task = Task.find(params[:id])
  end

  def update
    # PATCH /restaurants/:id
    @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to task_path(@task)
  end

  def destroy
    # DELETE /restaurants/:id
    @task = Task.find(params[:id])
    @task.destroy
  end

  private

  def task_params
    params.require(:task).permit(:title, :details)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_for(@task) do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :details %>
    <%= f.text_field :details, class: 'form-control' %>
  </div>

  <div class="check_box">
    <%= f.label :completed %>
    <%= f.check_box :completed, class: 'check_box' %>
  </div>

  <%= f.submit class: 'btn btn-primary' %>
<% end %>

app/views/tasks/edit.html.erb
<h1>Edit page</h1>
<%= render 'form', task: @task %>

<%= link_to "Back to list", '/tasks' %>

app/views/tasks/index.html.erb
<h1>My tasks</h1>
<div class="task-list">
  <% @tasks.each do |task| %>
      <p><%= check_box("task", task.id, {checked: task.completed}) %><%= link_to task.title, task_path(task) %></p>
  <% end %>
</div>
<br>
<br>
<br>
<%= link_to "Add new task", 'tasks/new' %>

app/views/tasks/new.html.erb
<h1>New task</h1>
<%= render 'form', task: @task %>

app/views/tasks/show.html.erb
<div class="main">
  <h1><%= @task[:title] %></h1>
  <%= link_to 'Edit', edit_task_path(@task), class: "btn btn-secondary"%>
</div>
<div class="container">
  <div class="details">
    <p><%= @task[:details] %></p>
  </div>
</div>
<br>
<div class="ceck-box">
  <p><%= check_box("task", @task.id, {checked: @task.completed}) %>
    <%= if @task.completed
      "This task is completed!"
    else
      "This task is not completed yet"
      end %><% %>
  </p>
</div>
<br>
<div>
  <%= link_to "Back to list", '/tasks' %>
</div>